
services:
  mongo:
    container_name: unifi_mongo
    image: mongo:3.6
    restart: unless-stopped
    volumes:
      - /home/hughboi/data/unifi/db:/data/db
      - /home/hughboi/data/unifi//dbcfg:/data/configdb
    networks:
      - unifi



  controller:
    container_name: unifi_controller
    image: "jacobalberty/unifi:latest"
    restart: unless-stopped   
    depends_on:
      - mongo
    init: true
    volumes:
      - /home/hughboi/data/unifi/dir:/unifi
      - /home/hughboi/data/unifi/data:/unifi/data
      - /home/hughboi/data/unifi/log:/unifi/log
      - /home/hughboi/data/unifi/cert:/unifi/cert
      - /home/hughboi/data/unifi/init:/unifi/init.d
      - /home/hughboi/data/unifi/run:/var/run/unifi
      # Mount local folder for backups and autobackups
      - /home/hughboi/data/unifi/backup:/unifi/data/backup
    user: unifi
    sysctls:
      net.ipv4.ip_unprivileged_port_start: 0
    environment:
      DB_URI: mongodb://mongo/unifi
      STATDB_URI: mongodb://mongo/unifi_stat
      DB_NAME: unifi
    labels:
      # - "traefik.enable=true"
      # - "traefik.http.routers.unifi.entrypoints=http"
      # - "traefik.http.routers.unifi.rule=Host(`unifi.hughboi.cc`)"
      # - "traefik.http.middlewares.unifi-https-redirect.redirectscheme.scheme=https"
      # - "traefik.http.routers.unifi.middlewares=unifi-https-redirect"
      # - "traefik.http.routers.unifi-secure.entrypoints=https"
      # - "traefik.http.routers.unifi-secure.rule=Host(`unifi.hughboi.cc`)"
      # - "traefik.http.routers.unifi-secure.tls=true"      
      # - "traefik.http.services.unifi.loadbalancer.server.port=8443"
      - "traefik.enable=true"
      - "traefik.http.routers.unifi.entrypoints=https"
      - "traefik.http.routers.unifi.rule=Host(`unifi.hughboi.cc`)"
      - "traefik.http.routers.unifi.tls.certresolver=cloudflare"
      - "traefik.http.services.unifi.loadbalancer.server.port=8443"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.unifi-http.entrypoints=http"
      - "traefik.http.routers.unifi-http.rule=Host(`unifi.hughboi.cc`)"
      - "traefik.http.routers.unifi-http.middlewares=unifi-https-redirect"
      ## DIUN
      - "diun.enable=true"
    ports:
      - "3478:3478/udp" # STUN
      - "6789:6789/tcp" # Speed test
      - "8080:8080/tcp" # Device/ controller comm.
      - "8443:8443/tcp" # Controller GUI/API as seen in a web browser
      - "8880:8880/tcp" # HTTP portal redirection
      - "8843:8843/tcp" # HTTPS portal redirection
      - "10001:10001/udp" # AP discovery
    networks:
      - unifi
      - proxy




  logs:
    container_name: unifi_logs
    image: bash
    restart: always
    depends_on:
      - controller
    logging:
      driver: loki
      options:
        loki-url: "https://loki.hughboi.cc/loki/api/v1/push"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    command: bash -c 'tail -F /unifi/log/*.log'
    volumes:
      - /home/hughboi/data/unifi/log:/unifi/log

# volumes:
#   db:
#   dbcfg:
#   data:
#   log:
#   cert:
#   init:
#   dir:
#   run:

networks:
  unifi:
  proxy:
    external: true
