services:
  invidious:
    container_name: invidious    
    image: quay.io/invidious/invidious:latest
    restart: unless-stopped
    depends_on:
      - invidious-db    
    environment:
      # https://github.com/iv-org/invidious/blob/master/config/config.example.yml
      INVIDIOUS_CONFIG: |
        db:
          dbname: ${POSTGRES_DB}
          user: ${POSTGRES_USER}
          password: ${POSTGRES_PASSWORD}
          host: invidious-db #dns name of docker container below
          port: 5432
        check_tables: true
        signature_server: inv_sig_helper:12999
        visitor_data: ${VISITOR_DATA_KEY}
        po_token: ${PO_TOKEN}
        external_port: 443
        domain: "invidious.hughboi.cc"
        https_only: true
        statistics_enabled: false
        hmac_key: ${HMAC_KEY}
    logging:
      options:
        max-size: "1G"
        max-file: "4"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.invidious.entrypoints=http"
      - "traefik.http.routers.invidious.rule=Host(`invidious.hughboi.cc`)"
      - "traefik.http.middlewares.invidious-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.invidious.middlewares=invidious-https-redirect"
      - "traefik.http.routers.invidious-secure.entrypoints=https"
      - "traefik.http.routers.invidious-secure.rule=Host(`invidious.hughboi.cc`)"
      - "traefik.http.routers.invidious-secure.tls=true"
      - "traefik.http.services.invidious.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
      - invidious


  inv_sig_helper:
    container_name: invidious-sig-helper    
    image: quay.io/invidious/inv-sig-helper:latest
    security_opt:
      - no-new-privileges:true    
    restart: unless-stopped    
    init: true
    command: ["--tcp", "0.0.0.0:12999"]
    environment:
      - RUST_LOG=info
    cap_drop:
      - ALL
    read_only: true
    networks:
      - invidious


  invidious-db:
    image: docker.io/library/postgres:16
    container_name: invidious-db
    restart: unless-stopped
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - config:/config/sql
      - db_init:/docker-entrypoint-initdb.d/init-invidious-db.sh
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
    networks:
      - invidious

networks:
  invidious:
    driver: bridge
  proxy:
    external: true


volumes:
  postgresdata:
  config:
  db_init:    
