services:
  generator:
    image: wazuh/wazuh-certs-generator:0.0.2
    hostname: wazuh-certs-generator
    volumes:
      - /home/hughboi/data/wazuh/config/wazuh_indexer_ssl_certs/:/certificates/
      - /home/hughboi/data/wazuh/config/certs.yml:/config/certs.yml
