services:
  mautrix-discord:
    container_name: mautrix-discord
    image: dock.mau.dev/mautrix/discord:latest
    restart: unless-stopped
    volumes:
    - /home/hughboi/data/synapse/discord-mautrix-bridge/data:/data
    ports:
      - "29334:29334"
    # You'll also probably want this so the bridge can reach Synapse directly
    # using something like `http://host.docker.internal:8008` as the address:
    #extra_hosts:
    #- "host.docker.internal:host-gateway"
    networks:
      mautrix-discord:

  mautrix-discord-db:
    container_name: mautrix-discord-db    
    image: docker.io/postgres:16
    restart: always
    environment:
      - POSTGRES_USER={POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      mautrix-discord:

networks:
  mautrix-discord:

volumes:
  postgres:
