services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun
    restart: unless-stopped
    logging:
      driver: loki
      options:
        loki-url: "https://loki.hughboi.cc/loki/api/v1/push"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    env_file:
      - .env
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_TOKEN}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}  # Set a private IP address here
      - TZ=America/Denver
      # Server list updater
      - UPDATER_PERIOD=24h
    volumes:
      - /home/hughboi/data/soularr/gluetun:/gluetun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
    networks:
      - torrent
      - vpn
 
 
 
  navidrome:
    container_name: navidrome
    image: deluan/navidrome:latest
    restart: unless-stopped
    environment:
      ND_MUSICFOLDER: /data/music
      ND_DBPATH: /data/navidrome.db
      ND_SCANINTERVAL: 1h
      ND_LOGLEVEL: info
      ND_PORT: 4533
    logging:
      driver: loki
      options:
        loki-url: "https://loki.hughboi.cc/loki/api/v1/push"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    volumes:
      - /home/hughboi/data/soularr/navidrome/data:/data
      - /home/hughboi/data/soularr/navidrome/music:/music:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.navidrome.entrypoints=http"
      - "traefik.http.routers.navidrome.rule=Host(`navidrome.hughboi.cc`)"
      - "traefik.http.middlewares.navidrome-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.navidrome.middlewares=navidrome-https-redirect"
      - "traefik.http.routers.navidrome-secure.entrypoints=https"
      - "traefik.http.routers.navidrome-secure.rule=Host(`navidrome.hughboi.cc`)"
      - "traefik.http.routers.navidrome-secure.tls=true"
      - "traefik.http.services.navidrome.loadbalancer.server.port=4533"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
      - torrent


  lidarr:
    container_name: lidarr
    image: lscr.io/linuxserver/lidarr:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
    volumes:
      - /home/hughboi/data/soularr/lidarr/config:/config
      - /home/hughboi/data/soularr/lidarr/data:/data/music
    logging:
      driver: loki
      options:
        loki-url: "https://loki.hughboi.cc/loki/api/v1/push"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lidarr.entrypoints=http"
      - "traefik.http.routers.lidarr.rule=Host(`lidarr.hughboi.cc`)"
      - "traefik.http.middlewares.lidarr-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.lidarr.middlewares=lidarr-https-redirect"
      - "traefik.http.routers.lidarr-secure.entrypoints=https"
      - "traefik.http.routers.lidarr-secure.rule=Host(`lidarr.hughboi.cc`)"
      - "traefik.http.routers.lidarr-secure.tls=true"
      - "traefik.http.services.lidarr.loadbalancer.server.port=8686"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
      - torrent


  slskd:
    container_name: soulseek
    image: slskd/slskd
    restart: unless-stopped
    hostname: soulseek
    logging:
      driver: loki
      options:
        loki-url: "https://loki.hughboi.cc/loki/api/v1/push"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"  
    user: 1000:1000
    volumes:
      - /home/hughboi/data/soularr/soulseek/:/app
    environment:
      - TZ=America/Denver
      - SLSKD_REMOTE_CONFIGURATION=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.soulseek.entrypoints=http"
      - "traefik.http.routers.soulseek.rule=Host(`soulseek.hughboi.cc`)"
      - "traefik.http.middlewares.soulseek-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.soulseek.middlewares=soulseek-https-redirect"
      - "traefik.http.routers.soulseek-secure.entrypoints=https"
      - "traefik.http.routers.soulseek-secure.rule=Host(`soulseek.hughboi.cc`)"
      - "traefik.http.routers.soulseek-secure.tls=true"
      - "traefik.http.services.soulseek.loadbalancer.server.port=5030"
      - "traefik.docker.network=proxy"
    ports:
      - 5030:5030
      - 5031:5031
      - 50300:50300
    networks:
      - proxy
      - torrent



  soularr:
    container_name: soularr
    image: mrusse08/soularr:latest
    restart: unless-stopped
    hostname: soularr
    logging:
      driver: loki
      options:
        loki-url: "https://loki.hughboi.cc/loki/api/v1/push"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking" 
    user: 1000:1000
    environment:
      - TZ=America/Denver
      - SCRIPT_INTERVAL=300 # Script interval in seconds
    volumes:
      # "You can set /downloads to whatever you want but will then need to change the Slskd download dir in your config file"
      - /home/hughboi/soularr/data/downloads/:/downloads
      # Select where you are storing your config file.
      # Leave "/data" since thats where the script expects the config file to be
      - /home/hughboi/soularr/data:/data
    networks:
      - torrent



  qbittorrent:
    container_name: qbittorrent 
    image: lscr.io/linuxserver/qbittorrent
    restart: always
    depends_on:
      - gluetun
    logging:
      driver: loki
      options:
        loki-url: "https://loki.hughboi.cc/loki/api/v1/push"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    #network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - WEBUI_PORT=8085
    volumes:
      - /home/hughboi/data/soularr/qbittorrent:/config
      - /home/hughboi/data/soularr/qbittorrent/downloads:/downloads
    networks:
      - torrent
      - vpn



networks:
  proxy:
    external: true
  torrent:
  vpn: 
    driver: bridge